### PR TITLE
static: addition of build.js configuration

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by drjova** [comment]
`build.js` in `REQUIREJS_CONFIG` https://github.com/inveniosoftware/invenio-assets/pull/7

**Comment by jirikuncar** [comment]
@drjova `s/add/addition/` + can you add some insides about this file to commit message? Thanks

**Comment by drjova** [comment]
@jirikuncar done!

**Comment by jirikuncar** [comment]
IMHO `Invenio-Theme` should do `app.config.setdefault("REQUIREJS_CONFIG", 'js/build.js')` instead of *Invenio-Assets*. /cc @lnielsen

**Comment by lnielsen** [comment]
@jirikuncar Agreed.

**Comment by drjova** [comment]
:+1: done

**Pull request merged**
